### ISSUE TITLE
What does this mean: Element %s not found

### ISSUE THREAD

**Issue by LuckieCrab** [bcharron/block-finder#1]
Just trying to run the program, 
`go run finder2.go -blockName minecraft:netherrack`
But I get the error mentioned in the title. What does it mean, I have no idea.

**Comment by bcharron** [comment]
The "%s" was a bug, it should have shown the name of the tag that the program failed to find.

The error could mean that the file is corrupted, or its format changed since I made this program.

**Comment by LuckieCrab** [comment]
Wich file actually? The level.dat file?
